<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-76M5JGF" failures="1" tests="4" name="Test" time="46.958" errors="0" timestamp="2024-05-04T16:45:02 IST">
  <testcase classname="testngPackage.LoginExample" name="login" time="9.735"/>
  <testcase classname="testngPackage.LoginExample" name="login" time="3.293">
    <failure type="java.lang.AssertionError" message="expected [https://www.saucedemo.com/v1/inventory.html] but found [https://www.saucedemo.com/v1/]">
      <![CDATA[java.lang.AssertionError: expected [https://www.saucedemo.com/v1/inventory.html] but found [https://www.saucedemo.com/v1/]
at testngPackage.LoginExample.login(LoginExample.java:94)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- login -->
  <testcase classname="testngPackage.LoginExample" name="login" time="3.718"/>
  <testcase classname="testngPackage.LoginExample" name="login" time="7.892"/>
</testsuite> <!-- Test -->
